#ifndef ERRORS_H
#define ERRORS_H

// World error codes
#define ERROR_WORLD_CELL_LIMIT_EXCEEDED 1

// Cell error codes
#define ERROR_CELL_CELL_RADIUS_UNDER_MIN 2
#define ERROR_CELL_CELL_RADIUS_OVER_MAX 3

// CellConnections error codes
#define ERROR_CELLCONNECTIONS_STRUCT_MEMORY_UNALLOCATED 4
#define ERROR_CELLCONNECTIONS_CELL_POINTER_ARRAY_MEMORY_UNALLOCATED 5
#define ERROR_CELLCONNECTIONS_CELL_ARRAY_MEMORY_UNALLOCATED 6
#define ERROR_CELLCONNECTIONS_CELL_MEMORY_UNALLOCATED 7
#define ERROR_CELLCONNECTIONS_CONNECTIONS_OVER_MAX 8
#define ERROR_CELLCONNECTIONS_CONNECTION_SIZE_OVER_MAX 9
#define ERROR_CELLCONNECTIONS_STRUCT_MEMORY_FULL 10
#define ERROR_CELLCONNECTIONS_NEW_CONNECTION_OVER_MAX_COUNT 11

// Global error codes
#define ERROR_GLOBAL_NULLPOINTER_ARGUMENT 100

#endif
