#ifndef ERRORS_H
#define ERRORS_H

// error codes to use
#define ERROR_ENTITY_LIMIT_EXCEEDED 1
#define ERROR_CELL_RADIUS_UNDER_MIN 2
#define ERROR_CELL_RADIUS_OVER_MAX 3
#define ERROR_CELL_CONNECTIONS_OVER_MAX 4
#define ERROR_SINGLE_CELL_CONNECTION_SIZE_OVER_MAX 5

#endif
